### ISSUE TITLE
why socket.io on client side?

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/workway#2]
Did you use `socket.io` for cross-browser compatibility (and fallback)?

Because socket library is quite heavy and I was wondering if it was possible to use native `WebSocket` on client side.

**Comment by WebReflection** [comment]
socket.io simplifies the "hand shaking" and the tracking of each client. I might get rid of it but I won't have any time soon (and no priority whatsoever since socket.io already works and I use this to drive Internet on Things devices)

**Comment by WebReflection** [comment]
btw @albertosantini , in case it's not clear, for WebWorkers socket.io is not needed neither used at all, it's needed only for Node.js driven files. In case there was some confusion about it.

**Comment by albertosantini** [comment]
It is clear. 

The use case is when `workway` is used for loading Node.js `workers`, like

`workway("node://finance.js")`

And 60KB (`sokect.io.js`) are loaded from the backend.

Agreed: an enhancement.

**Comment by WebReflection** [comment]
> And 60KB (sokect.io.js) are loaded from the backend.

I know it's not super lightweight, but I also know it solved on both client and server side in a super battle tested way.

I'm not sure I have the time to take care of all possible quirks socket.io took care already in the last (10?) years, so for now I'll leave it as it is.

Maybe if you use `compression` with express it's not that bad? I haven't checked myself.

**Comment by WebReflection** [comment]
you know what? I forgot about this:
https://github.com/uNetworking/uWebSockets

**Comment by albertosantini** [comment]
I second it only if there are not problems with Windows box. :)

**Comment by WebReflection** [comment]
right, uWS is indeed closer to the metal, but `ws` module should be fine.

However, the more I'm implementing the "_lightweight_" socket.io ease, the more I realize it's complicated to provide such easy to use interface in a tiny package.

Not sure I'll manage in reasonable time, but worth giving it a shot.

**Comment by WebReflection** [comment]
I gave it a shot, it's called [pocket.io](https://github.com/WebReflection/pocket.io) and workway client side overhead is now about 1K instead of 60K.

I hope this works for you.

**Comment by albertosantini** [comment]
Tested with ConPA.

It is ok. 
Thanks a lot.
