### ISSUE TITLE
Does not expose stream methods

### ISSUE THREAD

**Issue by fijiwebdesign** [WebReflection/workway#3]
I'm using the `/examples/workaway-node`

creating a `worker/stream.js`

```
const workway = require('workway');
const fs = require('fs');

const file = '../assets/test.txt'

// export any namespace or even modules
workway(fs.createReadStream(file));
```

In `www/js/index.js` on client side I have: 

```
workway('node://stream.js').then(async ({worker, namespace:stream}) => {

  console.log('stream', stream)
  stream.on('data', data => {
    console.log('read data', data.toString())
    stream.read()
  })
  stream.on('end', data => {
    console.log('stream end', data)
  })
  stream.on('error', error => {
    console.log('stream error', error)
  })
  stream.read()
});
```

I get the error in browser console: 

> index.js:4 Uncaught (in promise) TypeError: stream.on is not a function
>    at workway.then (index.js:4)

From the example you have:

```
const cpus = await os.cpus();
```

So I assume you can call any method of the exposed object? But why is `os.cpus` exposed but not `stream.on`?

**Comment by WebReflection** [comment]
I don't think streams make any sense in here, but also events are not forwarded. You can export methods that returns serializable data, streams, while streaming, are not part of it.

**Comment by fijiwebdesign** [comment]
Would there be a way of exposing streams? If yes it would enable exposing any JS. 

This may be feasible in environments like browser's service workers and between local tcp ports and general IPC.

Please let me know if I should move this discussion somewhere else as it's a question at this point. 

Question is it possible to serialize a stream by recursively serializing every possible method invocation. This could be done by wrapping the unserialized object at each end with a Proxy that will message the other end on a function invocation, reference resolution, get/set, promise resolution etc. The recursively wrapping the resulting response. 

I'm wondering what your thoughts and if you'd like such a contribution to the lib. 

It would be slow for sure but may be feasible for some generic purposes and super cool.

**Comment by WebReflection** [comment]
The overhead / circle for having streams through a worker based on sockets is probably not worth the hassle, unless I am missing a specific use case I can't see right now.

However, you can create your stream exporter outside this project scope and use it like any other module.
