### ISSUE TITLE
100% CSP?

### ISSUE THREAD

**Issue by loganpowell** [WebReflection/workway#4]
Dude, I'm looking through your work and am astonished at how many good ideas you have.

I'm currently looking for something like `workway` for some ClojureScript work I'm doing. I love the inversion of control idea you're bringing to the table with WebWorkers.

I'm thinking that I could somehow wrap `workway` to enable ClojureScript interop via [`core.async`] (CSP) channels. You think you're API would be amenable to that sort of thing? Sorry if this seems like a stupid question, I don't have much experience working with JavaScript.

[`core.async`]: https://clojure.org/news/2013/06/28/clojure-clore-async-channels

**Comment by WebReflection** [comment]
Thanks @loganpowell, glad you appreciate some of my work.

I'm afraid I have **zero** ClojureScript knowledge so I wouldn't know where to start answering, or even how.

However, if by _channels_ you mean streams, then workway might not be the right tool but WebSockets could, and in such case have a look at [pocket.io](https://github.com/WebReflection/pocket.io#pocketio).

**Comment by loganpowell** [comment]
No worries, I'll look into it. Thanks again for publishing so many great things for us to enjoy.
