### ISSUE TITLE
How do I grab a reference to a function imported via `importScripts`?

### ISSUE THREAD

**Issue by loganpowell** [WebReflection/workway#5]
Hey man! So, I'm starting to dig into this and am a bit confused as to how the references within an instance of `workway` work. For example, in your [example](https://github.com/WebReflection/workway#example-client-side-only):

```javascript
importScripts(...[
  'app', 'auth', 'database', 'firestore', 'messaging', 'functions'
].map(name => `https://www.gstatic.com/firebasejs/5.0.1/firebase-${name}.js`));

workway({
  timestamp: Date.now(),
  initializeApp(config) {
    firebase.initializeApp(config); // <- How does workway know that `firebase` is what I want to call the scripts imported above?
  },
  FirebaseUser: class FirebaseUser {
    constructor() {
      this.uid = firebase.auth().currentUser.uid;
    }
    name() {
      return firebase.database()
                .ref('/users/' + this.uid)
                .once('value')
                .then(snapshot => ((
                  snapshot.val() && snapshot.val().username
                ) || 'Anonymous'));
    }
  }
});
```
How does workway know that `firebase` is what I want to call the scripts imported above?

**Comment by WebReflection** [comment]
`importScripts` simply evaluate synchronously a script, and if this has a global namespace/reference exported, you can use it right away.

Accordingly, what you see there is nothing different from what you'd see in the Firebase documentation.
